### ISSUE TITLE
Question about rsyslog GELF and timestamp

### ISSUE THREAD

**Issue by jothoma1** [elcamlost/elcamlost.github.io#1]
Hello,
thanks for your great article about rsyslog and GELF.
Its very useful !

I have just a simple question about timestamp for logs, i follow your guide and try to redirect a simple yum.log to our Graylog with rsyslog.
Everything works fine except for timestamp, i would like the field "_timestamp" generated by the normalization of the yum.log to be the one present in Graylog but it's not the case.
In graylog, the timestamp is the one generated when rsyslog send the log, not the timestamp of the log itself.

Have you found something to help in this case ?
Again thanks a lot for your help !
Johan

**Comment by elcamlost** [comment]
Hm.. I guess, you need to remove timestamp field from the template and use custom template specific for yum.log
For example, see proftpd example from the article. It doesn't use default template **gelf-ext** with _property(name="timegenerated" dateformat="unixtimestamp")_ as value for timestamp, but intstead uses custom template based on lognormalize rulebase.
I double checked my graylog proftpd stream to verify if it really works and it works as expected.

Default **gelf-ext** template only usable for applications which can write directly to syslog socket in plain syslog format. 

PS: thanks for your feedback. I'm glad that i can share my knowledge for the common benefit.

**Comment by jothoma1** [comment]
Thanks for your help
sorry but there is something that i dont understand...
When i look at your proftpd example i see 

> ruleset(name="proftpd") {
  action(type="mmnormalize" rulebase="/etc/rsyslog.d/rules/proftpd_xfer.rb")
  call graylog-ext
}

what is the "call graylog-ext" ? 
In my case i have checked if i remove the timestamp from the template gelf-ext it stopped working (nothing arrives to graylog)
When i have timestamp in the template and _timestamp in the lognormalize rule, rsyslog takes the timestamp from the template and not the one from the rule.
It's not easy to see, in my case i saw this when i start implementing this method, it transfered the old yum.log lines and everything arrives with the timestamp of the day instead of the timestamp of the yum action (the one in the log file)

here is my yum.rb :

> version=2
rule=yum:%_timestamp:date-rfc3164{"format":"timestamp-unix"}% %_yum_action:word% %_yum_package:word%

Thanks again !

**Comment by elcamlost** [comment]
> what is the "call graylog-ext" ?

it is rsyslog function call. See [the docs for details](https://rsyslog.readthedocs.io/en/latest/rainerscript/rainerscript_call.html).

Next about your issue.
You right, my first advice was completely wrong. _timestamp_ is required field and you cannot send gelf message without it. But original advice from article (see proftpd example) with _timetamp_ and _\_timestamp_ fields should work.

According to [graylog sources](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java#L206) you **can** overwrite _timestamp_ value with _\_timestamp_ if underscored field goes after plain field. Because timestamp is part of set [RESERVED_SETTABLE_FIELDS](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L223).

What you can try is to define new template _gelf-yum_
```
template(name="gelf-yum" type="list") {
  constant(value="{\"version\":\"1.1\",")
  constant(value="\"host\":\"")                  property(name="hostname")
  constant(value="\",\"short_message\":\"")      property(name="msg" format="json")
  constant(value=",\"_application_name \":\"")   property(name="app-name")
  constant(value="\",\"level\":\"")              property(name="syslogseverity")
  constant(value="\",")                          property(name="$!all-json" position.from="2")
}
```
Please, note the absense of _timestamp_ field in the template.
and then define your rulebase
```
version=2
rule=yum:%timestamp:date-rfc3164{"format":"timestamp-unix"}% %_yum_action:word% %_yum_package:word%
```
Note that _timestamp_ field here is not prefixed with underscore.

Also you need new ruleset to bind _gelf-yum_ template with omfwd output and you cannot use _call gelf-ext_, because it binds different template. So your yum ruleset looks like this
```
ruleset(name="yum") {
  action(type="mmnormalize" rulebase="/path/to/yum.rb")
  action(
    type="omfwd"
    Target="graylog-server"
    Port="12201"
    Protocol="tcp"
    KeepAlive="on"
    template="gelf"
    StreamDriver="gtls"
    StreamDriverMode="1"
    StreamDriverAuthMode="x509/name"
    StreamDriverPermittedPeers="graylog-server"
    TCP_FrameDelimiter="0"
  )
}
```
the last one is a bit tricky. I never used two actions within one ruleset, but according to rsyslog docs it is fine. So you need to test it first and maybe rewrite to two different rulesets, where one call another.

Also check graylog and rsyslog versions. I'm using latest graylog 3.2 and rsyslog 8.1901.0

**Comment by jothoma1** [comment]
Thanks for your time, i have tried this but unfortunately it did not work
nothing arrives to graylog when i remove the **timestamp** field from the template (even if the yum.rb add this field)

I'm using latest graylog 3.2.4 and latest rsyslog 8.2002.0

it's strange
